WITH USER1 AS
(
    SELECT * FROM {{ source('USER_DATA', 'USER1') }}
),

USER2 AS
(
SELECT * FROM {{ source('USER_DATA', 'USER2') }}
)
SELECT USER1.USER_ID,USER1.USER_NAME,USER2.USER_NAME AS USER_NAME_2
FROM USER1
JOIN USER2 ON 
USER1.USER_ID=USER2.USER_ID